### ISSUE TITLE
ProcessImage w/ decoded source (Custom pixel accessor)

### ISSUE THREAD

**Issue by iamcarbon** [saucecontrol/PhotoSauce#1]
We do a lot of upstream processing of images (i.e. decoding, applying filters, etc).

It would be helpful to have an overload to ProcessImage that can provide decoded pixels directly to the processor.

For example:

```
interface IBitmapSource
{ 
  PixelFormat PixelFormat { get; }
  ColorPalette Palette { get; }
  Size Size { get; } 
  CopyPixels(Rectangle rect, Span<byte> buffer)
} 

public static void ProcessImage(IBitmapSource source, Stream output, ProcessImageSettings s);
```

**Comment by saucecontrol** [comment]
That's an interesting one.  I've been considering how I can make my processing pipeline more extensible without sacrificing the things that make it fast and lightweight.  The pipeline today is set up with a pull model built around (IWICBitbapSource)[https://msdn.microsoft.com/en-us/library/windows/desktop/ee690171(v=vs.85).aspx].  Using that interface allows me to request only the pixels I need immediately (typically enough to process a single output scanline) into a small buffer.  That, in turn, allows the upstream pixel source to avoid loading large images in memory all at once.  If you've already got the whole image decoded and sitting there, it's easy enough to fill that buffer, but then you end up copying the data when the original could be accessed instead.  I'll have to give that some thought.

Oh, and your example method signature leaves out the destination buffer/stream.  Was that just an oversight, or were you thinking the input buffer could be recycled to store the output?

**Comment by iamcarbon** [comment]
In that case, supporting a custom IWICBitmapSource would work just as well. 

The omission of the destination buffer was unintentional -- will still need that.

**Comment by saucecontrol** [comment]
Good deal.  I'm looking to replace my WIC stuff with managed implementations, so I'll have an analogous custom interface, but it'll work the same.  I'll keep this on my to-do list.

**Comment by mms-** [comment]
This is also something that would help us a lot. Currently we can't plug MagicScaler into our pipeline and maintain the performance benefits.

**Comment by saucecontrol** [comment]
I've finally got the architecture changes done to make this possible and have taken a stab at the interfaces.  Pixels can be fed into or pulled out of the pipeline using the IPixelSource interface, which is a simplified version of IWICBitmapPixelSource.  Here's how they go:

Option 1.  Feed pixels into MagicScaler pipeline, and complete processing in the pipeline.
```C#
var pix = new TestPatternPixelSource(1024, 768, PixelFormats.Bgr24bpp);
using (var fs = new FileStream(@"c:\img\testpattern.png", FileMode.Create))
	MagicImageProcessor.ProcessImage(pix, fs, new ProcessImageSettings { Width = 100, SaveFormat = FileFormat.Png });
```

Option 2.  Use MagicScaler to decode, color correct, resize, and sharpen... then pull the pixels out of the pipeline for continued processing.  This example resizes an image and draws it onto a System.Drawing.Bitmap, allowing further manipulation.
```C#
using (var pl = MagicImageProcessor.BuildPipeline(@"c:\img\big.jpg", new ProcessImageSettings { Width = 100 }))
using (var fs = new FileStream(@"c:\img\small.png", FileMode.Create))
using (var bmp = new Bitmap(pl.PixelSource.Width, pl.PixelSource.Height, PixelFormat.Format24bppRgb))
{
	var rec = new Rectangle(0, 0, bmp.Width, bmp.Height);
	var lck = bmp.LockBits(rec, ImageLockMode.ReadWrite, bmp.PixelFormat);
	pl.PixelSource.CopyPixels(rec, lck.Stride, (lck.Stride * lck.Height), lck.Scan0);
	bmp.UnlockBits(lck);
	bmp.Save(fs, ImageFormat.Png);
}
```

Option 3.  You can do IPixelSource both in and out

The IPixelSource provided as input can theoretically use any pixel format supported by [WIC](https://msdn.microsoft.com/en-us/library/windows/desktop/ee719797(v=vs.85).aspx), and the output will always be BGRA, BGR, or Grey.  Those Guids are included as static fields the `PixelFormats` class for ease of use.

I'll put an alpha build binary up on nugget shortly.

Does that cover your needs or are there some scenarios I've missed?

**Comment by iamcarbon** [comment]
This API looks perfect. Going to give it a whirl in the next few hours.

**Comment by iamcarbon** [comment]
Works perfectly!
