### ISSUE TITLE
Runnung MagicScaler API in .net core middleware

### ISSUE THREAD

**Issue by Astatira** [saucecontrol/PhotoSauce#100]
### Discussed in https://github.com/saucecontrol/PhotoSauce/discussions/99

<div type='discussions-op-text'>

<sup>Originally posted by **Astatira** November  3, 2022</sup>
Hi,

Thanks for the great library!
I wanna use your library to resize images beased on query string. I don't want to save the new image on hard disk  based on new settings, just want to response on the fly to the client side. how can I make a middleware for this in .net core ? 

In fact I need somthing like this answer (User711641945 posted) for SkiaSharp in this link 
[https://social.msdn.microsoft.com/Forums/en-US/8d5eb833-6911-4208-aadc-974c7c7da2a9/image-resize-and-crop?forum=aspdotnetcore](url)
but implemented by your library?

 </div>

**Comment by saucecontrol** [comment]
Discussions is the right place for this.  Please don't spam issues for extra attention.
