### ISSUE TITLE
Exception when opening multipage tiff files on Windows Server 2012 R2 using `ProcessImage(Stream imgStream, Stream outStream, ProcessImageSettings settings)`

### ISSUE THREAD

**Issue by mgaffigan** [saucecontrol/PhotoSauce#14]
When opening multipage tiff files on a Windows Server 2012 R2, we receive an exception only when trying to open multipage tiff files.  Single-page tiff files from the same source open fine, and both single and multi-page tiff files open with Windows Photo Viewer on the same server.  Both files also open with `TiffBitmapDecoder` without issue.

The same tiff files can be opened on a Windows 10 1703 computer without issue using the same calling code.

Calling code:

            var source = FileStream.OpenRead("demo.tif");
            var settings = new ProcessImageSettings()
            {
                FrameIndex = page,
                // scale to thumbnail size
                Width = newImageSize.Width,
                Height = newImageSize.Height,
                // Crop is needed to compensate for the nonuniform pixel aspect ratio
                Crop = new gdi.Rectangle(0, 0, fullFrame.PixelWidth, fullFrame.PixelHeight),
                // Add the DPI metadata to the desired result
                DpiX = newImageDpi.X,
                DpiY = newImageDpi.Y,
                // Lanczos results in sharpness at the expense of ringing
                Interpolation = InterpolationSettings.Lanczos
            };

            settings.SaveFormat = FileFormat.Png;

            using (var msResult = new MemoryStream())
            {
                // Exception here.
                MagicImageProcessor.ProcessImage(source, msResult, settings);

                // SNIP: use msResult
            }

Exception:
```
System.IO.InvalidDataException: Image format not supported.  Please ensure the input file is an image and that a WIC codec capable of reading the image is installed. 
	---> System.Runtime.InteropServices.COMException: The component cannot be found. (Exception from HRESULT: 0x88982F50)

   at PhotoSauce.MagicScaler.Interop.IWICImagingFactory.CreateDecoderFromStream(IStream pIStream, Guid[] pguidVendor, WICDecodeOptions metadataOptions)

   at PhotoSauce.MagicScaler.WicDecoder.<>c__DisplayClass20_0.<.ctor>b__0()

   at PhotoSauce.MagicScaler.WicDecoder.checkDecoder(Func`1 factory)

   --- End of inner exception stack trace ---

   at PhotoSauce.MagicScaler.WicDecoder.checkDecoder(Func`1 factory)

   at PhotoSauce.MagicScaler.WicDecoder..ctor(Stream inFile, WicProcessingContext ctx)

   at PhotoSauce.MagicScaler.MagicImageProcessor.ProcessImage(Stream imgStream, Stream outStream, ProcessImageSettings settings)
```
 
Every multi-page tiff I have tried seems to trigger the issue, but the one I was using is http://s000.tinyupload.com/index.php?file_id=01002933363618854391

**Comment by mgaffigan** [comment]
As a workaround, I'm using https://github.com/mgaffigan/PhotoSauce/commit/461c4e082be54374c7d0582efa509babbd6b429d which permits me to explicitly specify the decoder CLSID.  That seems to permit the use of in-memory streams without causing the exception.

I can send a PR if you want one.  I'd probably switch from `Guid` to using your preexisting `FileFormat` enum, though.

**Comment by saucecontrol** [comment]
Man, that is a strange one.  I've just tried a second Windows Server 2012 R2 box, and it's also working there.  I've got one on .NET 4.6.1 and one on 4.6.2.  I don't think I have any as old as 4.6, so I might set something up when I have time.

Hopefully I can figure out the actual issue, because the codec auto-detection is pretty important.  I'll keep your workaround in mind, though.  There might be a good reason to add a decoder hint anyway at some point.

**Comment by saucecontrol** [comment]
@mgaffigan I've finally set up a new Windows Server 2012 R2 VM, minimally patched and with only .NET 4.6... and I still can't get this to repro in either 32-bit or 64-bit.  I don't suppose you found anything else unusual about the server(s) in question?

**Comment by saucecontrol** [comment]
This should be solved in the current builds as the default codec registration includes only Microsoft-authored codecs, and the new `CodecManager` allows removing and reordering codecs in the event it's necessary to resolve conflicts.
