### ISSUE TITLE
After update the solution to .NET 8 version the NativeCodecs dependency started to fail

### ISSUE THREAD

**Issue by pvoliveira** [saucecontrol/PhotoSauce#143]
After updating the solution to .NET 8 version (from .NET 6) the NativeCodecs namespace started to show as missing.

It seems to be that the target framework is missing in the NativeCodecs project.

**Comment by saucecontrol** [comment]
Do you have a minimal repro?

What versions of the packages and SDK are you using?  Did you get an actual error message during build, or are you just missing intellisense?

**Comment by pvoliveira** [comment]
I was busy, I will create a test project to replicate my scenario, and I hope that it will make things clearer. As soon as possible I will update this issue.

**Comment by saucecontrol** [comment]
Closing due to lack of detail.  Feel free to re-open if you can provide a repro.
