### ISSUE TITLE
Exception when running in container

### ISSUE THREAD

**Issue by Zebusch** [saucecontrol/PhotoSauce#15]
Hi! I have created a image scaling application in .NET Core 2 which works just fine when running it like a console application. When i run it in Docker it throws errors:

`"Could not load type 'PhotoSauce.MagicScaler.Interop.WICImagingFactory2' from assembly 'PhotoSauce.MagicScaler, Version=0.8.4.0, Culture=neutral, PublicKeyToken=null'."`

Not sure if i am doing something wrong but i would assume that i would not need to modify my code to get it to work in a container?

EDIT: I have also tried the same code on Mac/Docker with the same result as with PC/Docker.

**Comment by saucecontrol** [comment]
Had a chance to look this morning, and it appears there aren't any Docker images that contain the required WIC components.  MagicScaler won't work in Docker unless/until that changes or unless/until I can replace the WIC dependency with platform-native codecs and color management.

https://success.docker.com/article/does-docker-for-windows-server-2016-support-gui-based-applications

**Comment by dev-siberia** [comment]
The same problem with the publication of the project ASP.NET Core 2.0 on Ubuntu 16.04 without Docker(
