### ISSUE TITLE
Decoder FrameRange validation is not valid

### ISSUE THREAD

**Issue by MaceWindu** [saucecontrol/PhotoSauce#151]
https://github.com/saucecontrol/PhotoSauce/blob/3a4f092c701b6f0990c1e8b388c535d06ac863e8/src/MagicScaler/Utilities/MiscExtensions.cs#L100

```cs
return (uint)start <= (uint)end && (uint)length <= (uint)end;
```

should be

```cs
return (uint)start <= (uint)end && (uint)length >= (uint)end;
```

Trying to extract first frame from multi-frame image and this check makes it impossible.

**Comment by saucecontrol** [comment]
Thanks, you're right. That was actually meant to be

```c#
return (uint)start <= (uint)end && (uint)end <= (uint)length;
```

**Comment by saucecontrol** [comment]
Fixed in https://github.com/saucecontrol/PhotoSauce/commit/62d101df3c76b2adfc95af289f84f3957f51e549
