### ISSUE TITLE
Build warning with net8.0 app

### ISSUE THREAD

**Issue by silvioboehme** [saucecontrol/PhotoSauce#152]
Just create a empty/basic console app with .net8.0 as target framework.
Add PhotoSauce.MagicScaler 0.14.1 and build this empty console app.

.nuget\packages\photosauce.magicscaler\0.14.1\buildTransitive\netcoreapp3.0\PhotoSauce.MagicScaler.targets(3,3): warning : MagicScaler is no longer hardware accelerated on net8.0. Upgrade your TargetFramework to net6.0 or later (or use an older version of the library) for the best performance. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning.

This doesn't make sense.

**Comment by saucecontrol** [comment]
🤦‍♂️ I didn't create the empty folder for net6.0+ to disable the warning there.  I'll publish a new package shortly.

**Comment by saucecontrol** [comment]
New release is up.  Thanks for letting me know!
