### ISSUE TITLE
"The component initialization has failed" error.

### ISSUE THREAD

**Issue by Rufio2031** [saucecontrol/PhotoSauce#168]
I recognize this likely isn't a problem with the library itself, but we're having trouble identifying the root cause of the error:
"The component initialization has failed".

We believe the issue is somewhere withing the realm of converting a CMYK image to RGB using the default ColorSpaceMode in ProcessImage(). We are using Windows Server 2022 and Windows 11, and believe we have the updated codecs but also aren't super confident in that realm. We're not sure if we need to enable something, or install something, or if there are windows configurations that need to be applied.

Here are a couple call stacks.

`at PhotoSauce.MagicScaler.WicTransforms.AddPixelFormatConverter(PipelineContext ctx, Boolean allowPbgra)\r\n   at PhotoSauce.MagicScaler.Transforms.MagicTransforms.AddNormalizingFormatConverter(PipelineContext ctx, Boolean lastChance)\r\n   at PhotoSauce.MagicScaler.MagicImageProcessor.buildPipeline(PipelineContext ctx, Boolean closedPipeline)\r\n   at PhotoSauce.MagicScaler.MagicImageProcessor.ProcessImage(Stream imgStream, Stream outStream, ProcessImageSettings settings)\r\n`

`at PhotoSauce.MagicScaler.WicTransforms.AddColorspaceConverter(PipelineContext ctx)\r\n   at PhotoSauce.MagicScaler.Transforms.MagicTransforms.AddColorspaceConverter(PipelineContext ctx)\r\n   at PhotoSauce.MagicScaler.MagicImageProcessor.buildPipeline(PipelineContext ctx, Boolean closedPipeline)\r\n   at PhotoSauce.MagicScaler.MagicImageProcessor.ProcessImage(Stream imgStream, Stream outStream, ProcessImageSettings settings)\r\n`

If there is any guidance on this we would be grateful to hear it. Attaching an image that we are able to repro with in our environments.
![Channel_digital_image_CMYK_color (1)](https://github.com/user-attachments/assets/a4954f51-5712-43e5-95a5-573d73a1e796)

**Comment by Rufio2031** [comment]
Closing this as I found the discussions area. Sorry.

**Comment by saucecontrol** [comment]
We should have a better error message here.  Reopening to track that.

**Comment by saucecontrol** [comment]
This is handled better in v0.15.0.  Some conversions will still be missing on Server Core, but the error message will be more useful.
