### ISSUE TITLE
How to determine future scaled image size

### ISSUE THREAD

**Issue by alvipeo** [saucecontrol/PhotoSauce#17]
Suppose I have an image file and I need to scale it to some targetWidth (or targetHeight). There must be something like that in the code but I couldn't find it. I found how to get image size with ImageFileInfo. But there's definitely should be the code which calculates the resulting size of the image. Please give me a hint.

I can write the calculation myself but if there's existing one, I'd like to be on the same page.

**Comment by saucecontrol** [comment]
There isn't currently anything in the public API that returns that information without actually doing the processing (again, it's in `ProcessImageResults.Settings` after processing is complete).  It wouldn't be too difficult to expose that, but I'd need to make some changes to prevent user errors like normalizing/calculating the settings against one image and then attempting to them on a different image.

**Comment by alvipeo** [comment]
I ask because I store processed images with the following name template `filename_srcWidth_srcHeight_scaledWidth_scaledHeight.jpg`. This way if I need to find the image scaled to some limits I can easily find it just by looking at file name. And I don't need any other processing or reading any kind of metadata.

**Comment by saucecontrol** [comment]
Gotcha.  I do basically the same thing [here](https://github.com/saucecontrol/PhotoSauce/blob/master/src/WebRSize/CacheFileNamingStrategy.cs) but it relies on some internal methods.  I'll see what I can work out for getting those public.

**Comment by alvipeo** [comment]
Yeah, that would be great! Thank you. Please let me know here.

**Comment by saucecontrol** [comment]
This is present in v0.9.0.  Usage is something like:

```C#
var settings = new ProcessImageSettings { Width = 400 };
var imgInfo = new ImageFileInfo(inImgPath);
var calculated = ProcessImageSettings.Calculate(settings, imgInfo);

Console.WriteLine($"Calculated Height: {calculated.Height}");
```
