### ISSUE TITLE
How can I convert PNG to JPG

### ISSUE THREAD

**Issue by MarcelVersteeg** [saucecontrol/PhotoSauce#171]
How I read the documentation of `MagicImageProcessor.ProcessImage` and `ProcessImageSettings`, setting the `ProcessImageSettings.EncoderOptions` to the options for the desired output format will convert the image.

Now I have a PNG image with transparency that I want to convert to a JPG. I do this as follows:
```
using (MemoryStream outputStream = new())
{
    MagicImageProcessor.ProcessImage(data/*of type ReadOnlySpan<byte>*/,
                                     outputStream,
                                     new ProcessImageSettings
                                            {
                                                EncoderOptions = new JpegEncoderOptions(100, ChromaSubsampleMode.Default),
                                                Height = height,
                                                ResizeMode = CropScaleMode.Stretch,
                                                Width = width
                                            });
}
```

However, the resized image is still of the PNG type. I can see that because the resized image still has the transparency, but also the call `ImageFileInfo.Load(outputStream).MimeType` still returns `image/png`. And finally, I see that the call to `MagicImageProcessor.ProcessImage` returns a `ProcessImageResult` where the `Settings` property contains `EncoderInfo` with the PNG encoder and the `EncoderOptions` with the `JpegEncoderOptions` I passed to the call. There I clearly see a mismatch.

Do I need something more to actually convert the image to a JPG (or vice versa, which also doesn't work)?

I am using NuGet package PhotoSauce.MagicScaler version 0.14.2

**Comment by saucecontrol** [comment]
There was previous discussion on this: https://github.com/saucecontrol/PhotoSauce/discussions/136

Short version is, passing `JpegEncoderOptions` only tells the pipeline what JPEG options to use *if JPEG output is chosen*.  If you pass an output file name to `ProcessImage` with a `.jpeg` extension, that will select JPEG output.  With `Stream` output, you will have to set the output format by calling [ProcessImageSettings.TrySetEncoderFormat](https://docs.photosauce.net/api/PhotoSauce.MagicScaler.ProcessImageSettings.html#PhotoSauce_MagicScaler_ProcessImageSettings_TrySetEncoderFormat_System_String_).

Absent a request to change format, the pipeline will automatically select output format based on the type of image.  If your source image has transparency, the pipeline will try to preserve that for you by selecting an output format that supports transparency (PNG).  You can remove the transparency by setting a [MatteColor](https://docs.photosauce.net/api/PhotoSauce.MagicScaler.ProcessImageSettings.html#PhotoSauce_MagicScaler_ProcessImageSettings_TrySetEncoderFormat_System_String_).

Again, see the discussion linked above for more detail and rationale.
