### ISSUE TITLE
PhotoSauce.NativeCodecs.Libheif Image format not supported error

### ISSUE THREAD

**Issue by rossvegas** [saucecontrol/PhotoSauce#172]
I am attempting to get a HEIC file decoded in a .net 8 console app in Visual Studio 2022 on windows 11, using the PhotoSauce.NativeCodecs.Libheif library.

```c#
using PhotoSauce.MagicScaler;
using PhotoSauce.NativeCodecs.Libheif;

CodecManager.Configure(codecs => {
    codecs.UseLibheif();
});

MagicImageProcessor.ProcessImage(@"img\big.heic", @"img\small.jpg", new ProcessImageSettings { Width = 400 });
``` 

I get the following error
```c#
Image format not supported.  Please ensure the input file is an image and that a codec capable of reading the image is registered.
``` 
and call stack
 
```c#
at PhotoSauce.MagicScaler.CodecCollection.GetDecoderForStream(Stream stm, IDecoderOptions options)
   at PhotoSauce.MagicScaler.CodecManager.GetDecoderForStream(Stream stm, IDecoderOptions opt)
   at PhotoSauce.MagicScaler.MagicImageProcessor.ProcessImage(String imgPath, String outPath, ProcessImageSettings settings)
```   

I have zipped up the HEIC file as github won't allow attaching them to an issue

[big.zip](https://github.com/user-attachments/files/17498905/big.zip)

Am I missing something here?

**Comment by saucecontrol** [comment]
Looks like that image wasn't handled by older libheif versions.  The [CI feed](https://dev.azure.com/saucecontrol/PhotoSauce/_artifacts/feed/photosauce_ci) has updated versions of the native library packages, and your sample works with the latest.

I'm planning a new NuGet release for hopefully not long after .NET 9.0 release.
