### ISSUE TITLE
Is the resulting image size available somewhere?

### ISSUE THREAD

**Issue by alvipeo** [saucecontrol/PhotoSauce#18]
Sorry, I couldn't find it. If I do this:

```
ProcessImageResult processImageResult = MagicImageProcessor.ProcessImage(sourceFileOrUri, fileStream, new ProcessImageSettings { Width = thumbnailSize.Width, Height = thumbnailSize.Height, ResizeMode = CropScaleMode.Max });
```
Is there any info on the resulting image size I can get anywhere?

**Comment by saucecontrol** [comment]
The `Settings` property on `ProcessImageResults` reflects the final settings used for processing.  That includes any calculated automatic settings as well as mutations to the dimensions or crop based on your `CropScaleMode`

**Comment by alvipeo** [comment]
Thank you! (please update the docs!)

**Comment by saucecontrol** [comment]
Will do, someday.

Samples and docs always end up at the bottom of my priority list somehow 😉
