### ISSUE TITLE
Padding Filter

### ISSUE THREAD

**Issue by iamcarbon** [saucecontrol/PhotoSauce#21]
Our pipeline supports adding padding to any side. It would be nice to be able to provide this via a custom transform or the settings.

e.g. 
```csharp
pipeline.AddTransform(new PadTransform(top, right, bottom, left));
```

**Comment by saucecontrol** [comment]
Sounds good.  I'd add a `Color` parameter as well, and I think I can get that in the next build.

**Comment by saucecontrol** [comment]
Added in v0.9.1
