### ISSUE TITLE
Ability to add custom Image Decoders

### ISSUE THREAD

**Issue by iamcarbon** [saucecontrol/PhotoSauce#22]
Proposed interface:

```csharp

AddDecoder(IDecoder decoder)

interface IDecoder 
{
   bool CanDecode(ReadOnlySpan<byte> headerBytes);
   IPixelSource Decode(Stream data);
}
```

Questions:

* Should pluggable decoders be prioritized over WIC?
* Should we support color profiles & metadata?
* Should we support any additional pixel formats within the decoded pixel source or should the decoder be responsible for converting to Bgra32, Bgr24, or Gray8 pixels?

**Comment by saucecontrol** [comment]
I've been thinking about this for a while, and I plan to start experimenting soon.  I'm quite excited about the possibility of high-performance managed codecs using the new HWIntrinsics in netcore, but I'd like to see how cleanly we can integrate with other platform-native codecs (e.g. libtiff, libpng, libjpeg-turbo) as well.

> Should pluggable decoders be prioritized over WIC?

I think the first step will be to make the WIC codecs themselves plug in to the pipeline through a standard interface.  That makes a good smoke test for the interfaces with minimal other impact to start.  Once they plug in, I would think they'd have a default priority that would allow other codecs to slot in either higher or lower in the list.

>Should we support color profiles & metadata?

I see this as a basic requirement of a codec, at least as far as extracting metadata blocks from a container.  I think parsing of individual metadata formats should be offloaded to dedicated components that can be shared between codecs.  Perhaps those can be pluggable too?

> Should we support any additional pixel formats within the decoded pixel source or should the decoder be responsible for converting to Bgra32, Bgr24, or Gray8 pixels?

My gut feeling is that each codec should do no more than decode the pixel formats supported by that image format and that pixel conversion should be offloaded, for the same reasons as the metadata.

**Comment by saucecontrol** [comment]
I think we can finally call this done, with https://github.com/saucecontrol/PhotoSauce/tree/master/src/NativeCodecs/Libheif as the first fully-fledged decoder plugin 😄
