### ISSUE TITLE
Best library to build a chart like an image

### ISSUE THREAD

**Issue by Meenakshise** [saucecontrol/PhotoSauce#26]
Hi,
We have to create a new chart with the attached template. could you please suggest me which library would be best to use for the chart. Quality of the image should not distort when it is viewed in laptop or ipad or ipod. please suggest a library. Earlier we were using system.drawing. But now we are trying the revamp the whole code to use a better approach. Please advise us.

C# should build this image using any library. All these has to be flexible. Not should be harded. Means chart is purely configurable. Based upon the configuration the rendering varies.
Also this should be an vector image format.

**Comment by Meenakshise** [comment]
![image](https://user-images.githubusercontent.com/5516586/52460864-6a4a8900-2b92-11e9-92af-79f99dfbb48a.png)

**Comment by iamcarbon** [comment]
MagicScaler is used to scale images. It does not provide a drawing API or support vectors. Did you mean to post this to a different library?

You may want to checkout ImageSharp, which supports drawing shapes, fonts, and other elements to a canvas. https://github.com/SixLabors/ImageSharp

**Comment by saucecontrol** [comment]
Yep, this library doesn't include any drawing capabilities, only image manipulation (heavy focus on resizing).  ImageSharp, SkiaSharp, or even System.Drawing can be used to build a chart like your example.
