### ISSUE TITLE
CropScaleMode.Max upscales the image ?

### ISSUE THREAD

**Issue by hheexx** [saucecontrol/PhotoSauce#30]
As I thought CropScaleMode.Max only downscales images if needed.
Looks like it also upscales so name is a little misleading.

Is there a mode that only downscales if needed?

**Comment by saucecontrol** [comment]
I don't believe there's anything misleading about the name.  It resizes to the max of your requested width or height while maintaining aspect ratio.  All modes will upscale or downscale as necessary to meet your requested output dimensions.

If you wish to prevent upscaling entirely, you can use `ImageFileInfo` to inspect your source image before resizing and clamp the requested output size to be no larger than the input.

**Comment by hheexx** [comment]
Found ImageFileInfo class now. It works.
Consider adding boolean to settings to disable upscaling. I think it may be common need...

**Comment by saucecontrol** [comment]
Yep, that sounds reasonable.  I built that option into the [WebRSize module](https://github.com/saucecontrol/PhotoSauce/blob/master/doc/web.md#allow-enlarge) but it makes sense to get it moved into the main processor.

**Comment by saucecontrol** [comment]
FYI, I decided to update the behavior of `CropScaleMode.Max` so it no longer upscales starting from v0.10.0.  There is a new `CropScaleMode.Contain` that maintains the old behavior.
