### ISSUE TITLE
Wish I had read this firs! This is windows only! Please mention earlier in documentation

### ISSUE THREAD

**Issue by richardlalancetteyoui** [saucecontrol/PhotoSauce#35]
Requirements
MagicScaler currently runs only on Windows. Although MagicScaler is compatible with (and optimized for) .NET Core, it requires the Windows Imaging Component to function. Work is in progress to allow MagicScaler to run on other platforms.

**Comment by saucecontrol** [comment]
Thanks for the feedback. I really have no idea how many people end up on this project with the intent to run it on a non-Windows platform. I'll see what I can do next time I tidy up the readme.  

Hopefully won't be much longer to remove the WIC requirement as well.

**Comment by richardlalancetteyoui** [comment]
I literally felt in love with dotnet core 3.1.
It's a beautiful piece of engineering. So fluid and easy to use!
But, i'm in an environment that will require image processing for dozens of platforms potentially and I want this to be fast!
Your work here seems amazing, so it is natural to bridge dotnet core and libraries like yours.

Simple :)

**Comment by Darren166** [comment]
Unfortunately I went down a similar route. We are using .net core 2.2 and did a really nice resizer for our images that was quick and high quality but then we had to deploy to a docker container running on Linux.....
Now we are trying to find something as good as your package but with the compatibility. It isn't easy!
Any idea on timescales?

**Comment by saucecontrol** [comment]
The most realistic timescale I can give is late this year.  I've got a funding commitment that should cover the time needed to work on it, so it will be a matter of carving that time out of my schedule and getting back up to speed on Linux (I haven't done any serious Linux work since the late 90s) and the current state of cross-platform native interop in .NET.  If someone out there has good x-plat .NET experience and wants to help out, that may accelerate things a bit.

**Comment by maxisam** [comment]
> Thanks for the feedback. I really have no idea how many people end up on this project with the intent to run it on a non-Windows platform. I'll see what I can do next time I tidy up the readme.
> 
> Hopefully won't be much longer to remove the WIC requirement as well.

You would be surprised. Because everything now is in the container. It is easier to do Linux than Windows in Kubernetes. Hope this project can get rid of WIC soon. It is a great project! Thanks!

**Comment by saucecontrol** [comment]
Finally got around to doing the doc update.  Still working on the Linux support, which is being tracked by #16

**Comment by richardlalancetteyoui** [comment]
> Thanks for the feedback. I really have no idea how many people end up on this project with the intent to run it on a non-Windows platform. I'll see what I can do next time I tidy up the readme.
> 
> Hopefully won't be much longer to remove the WIC requirement as well.

With the huge microsoft push to cross platform, this package is going to get hit more.
Any optimisation you do to images processing is huge in the server world.

Kudos!
