### ISSUE TITLE
Update example code on README.md

### ISSUE THREAD

**Issue by eman1986** [saucecontrol/PhotoSauce#4]
the code example on the readme is incorrect

the example code assumes the code is:

`ProcessImage(string, FileStream, ProcessImageSettings)`

but it is actually

`ProcessImage(string, Stream, ProcessImageSettings)`

as a first time user trying to figure it out, thats very frustrating

**Comment by saucecontrol** [comment]
Thanks for the feedback, but I'm not following.  The sample code is valid.

Are you saying the sample made you think you could only output to a file, or did you have a problem running it?

**Comment by eman1986** [comment]
Yes I get an error stating that I need to be using Stream and not FileStream. I copied the example on the readme and it gives me that same error.

**Comment by saucecontrol** [comment]
[Stream](https://msdn.microsoft.com/en-us/library/system.io.stream(v=vs.110).aspx) is an abstract class, so you can't possibly pass one to anything.  You need to use a concrete implementation of `Stream`, and [FileStream](https://msdn.microsoft.com/en-us/library/system.io.filestream(v=vs.110).aspx) is one such implementation.  I can't imagine what's giving you the error you mentioned, unless you're using some other class called `FileStream` and not a `System.IO.FileStream`.

**Comment by eman1986** [comment]
I'm using `System.IO.FileStream` and still seeing that error, I'm attaching what VS is displaying to me.

![cserror](https://user-images.githubusercontent.com/2343334/27801547-99be0bf8-5fec-11e7-8d3b-8178e61f6c3e.png)

**Comment by saucecontrol** [comment]
I'm baffled.  The first overload in that list matches the method it says it can't resolve.  I've just tried the example code in a new project, and it's working as expected.  Here's my VS (tried it in 2015 and 2017, .NET 4.6 and .NET Core 1.1) showing it has resolved the correct (string, Stream, ProcessImageSettings) overload with those arguments.

![image](https://user-images.githubusercontent.com/7929102/27802572-7045b900-5fd9-11e7-87f1-03c213270249.png)

I did find a problem with the nuget package, though.  It has a frameworkAssembly reference to System.Runtime, which might be causing a conflict between versions of some of the System classes.  If you're on the full .NET Framework, can you check your project references and see if System.Runtime is there?  If you see it, try removing it.

**Comment by eman1986** [comment]
I do see System.Runtime in there, but it's not letting me remove it. I'm using .NET core 1.1 btw

**Comment by saucecontrol** [comment]
Ah, ok.  it needs to be there for .NET Core.  I'm still investigating.  You on VS 2017?

**Comment by eman1986** [comment]
Yes, so interesting enough, it builds without error but I still see the error. I'm curious if ReSharper is the problem here. I tried it on another copy of VS and it seems to be fine.

I'm guessing ReSharper is just being super picky or maybe I discovered a bug :)

**Comment by saucecontrol** [comment]
Good to know.  I reckon it's a conflict with resolving those System classes, but I'm not sure if ReSharper is at fault or if I've done something strange.  I'll do a bit more testing.  Thanks for the heads-up anyway.
