### ISSUE TITLE
Trying to resize gif with animation

### ISSUE THREAD

**Issue by ltoshev** [saucecontrol/PhotoSauce#40]
Hi I am trying to resize a gif while keeping the animation.

I get a resized image that is no longer animated.

How can this be fixed?

Kind Regards,
Lyubomir

**Comment by ltoshev** [comment]
var outMs = new MemoryStream();
    var settings = new ProcessImageSettings { Width = rescaledWidth, Height = rescaledHeight };
    orgImage.Position = 0;
    MagicImageProcessor.ProcessImage(orgImage, outMs, settings);

Here is my code

**Comment by saucecontrol** [comment]
Full animated GIF output is not yet supported, but I'm working on that for the next version.  I will leave this open as a tracking issue for that effort.

The basic roadmap:

- [x] Support animated GIF playback in an internal buffer for proper decode of all frames
- [ ] Support output of full animated frame set, preserving metadata
- [ ] Optimize output GIF size, using sub-frame encoding and transparent overlay
- [ ] Improve quality and speed by replacing WIC components with custom code

**Comment by saucecontrol** [comment]
Animated GIF output works now, available for testing in the last CI build: https://dev.azure.com/saucecontrol/PhotoSauce/_packaging?_a=feed&feed=photosauce_ci

**Comment by ltoshev** [comment]
I've managed to implement this on my end by using the following code and a helper library. Its not optimal but works for now.

private static MemoryStream ResizeGif(MemoryStream orgImage, int rescaledWidth, int rescaledHeight)
        {
            var outMs1 = new MemoryStream();
            using (var an = new AnimatedGif.AnimatedGifCreator(outMs1, 33, 0))
            {
                var settings = new ProcessImageSettings { ColorProfileMode = ColorProfileMode.Preserve, Width = rescaledWidth, Height = rescaledHeight };
                orgImage.Position = 0;
                ImageFileInfo iff = ImageFileInfo.Load(orgImage);
                for (var i = 0; i < iff.Frames.Count; i++)
                {
                    settings.FrameIndex = i;
                    orgImage.Position = 0;
                    using (var outMs = new MemoryStream())
                    {
                        MagicImageProcessor.ProcessImage(orgImage, outMs, settings);
                        var img = Image.FromStream(outMs);
                        an.AddFrame(img, 1);
                    }
                }
            }
            outMs1.Position = 0;
            return outMs1;
        }

I've have only one issue. Some how after the resize the transparent background of a gif gets lost and is completely black.

**Comment by ltoshev** [comment]
![florian-vogt-cyclop-f-walk](https://user-images.githubusercontent.com/1788597/77897730-bec33300-7282-11ea-8bfe-69b0da68b1df.gif)

When converted this image turns with black background. How can we solve this, what option I need to set to the processor?

**Comment by saucecontrol** [comment]
The output is correct with default settings in the new version -- no helper is necessary.  You can try the latest build by adding the CI feed to your csproj and using a wildcard version reference.

```XML
<PropertyGroup>
    <RestoreAdditionalProjectSources>https://pkgs.dev.azure.com/saucecontrol/PhotoSauce/_packaging/photosauce_ci/nuget/v3/index.json</RestoreAdditionalProjectSources>
</PropertyGroup>

<ItemGroup>
    <PackageReference Include="PhotoSauce.MagicScaler" Version="0.10.*" />
</ItemGroup>
```

The output when resized with the following code:

```C#
using (var fs = File.OpenWrite(outFile))
{
    MagicImageProcessor.ProcessImage(inFile, fs, new ProcessImageSettings { Width = 300, Height = 300, ResizeMode = CropScaleMode.Max });
}
```

Is this:

![output](https://user-images.githubusercontent.com/7929102/77899877-11283380-7232-11ea-98e7-386e3cd681fd.gif)

Your sample image looks like it is aliased against a black background, which is why the outer lines are jaggy and black.  That effect is accentuated when you resize.  You may have better luck setting an explicit white MatteColor in the processing settings.

That output looks like this:

![gifresmag2](https://user-images.githubusercontent.com/7929102/77900770-64e74c80-7233-11ea-98f4-cc5138c05190.gif)

**Comment by brutoledo** [comment]
Any predictions when these support changes will be released in the production feed?

**Comment by saucecontrol** [comment]
I reckon sometime in the next week.  Just have a couple more small changes I'd like to get into the next release.

**Comment by saucecontrol** [comment]
v0.11 is up on NuGet and has the animated GIF support
