### ISSUE TITLE
PixelSource in processor has destination's dimensions

### ISSUE THREAD

**Issue by mikekov** [saucecontrol/PhotoSauce#43]
Hello, I'm trying to create an image minify function and I ran across this issue where imageProcessor.PixelSource.Width does not report original image size anymore.

Background: I want to write a function that creates thumbnails but never enlarges images. Given an NxN box it needs to resize image to fit (preserving aspect ratio), but keep images smaller than NxN pixels intact (pass-thru).

One way to accomplish this would be to create image processor and examine size of input image before processing it. Alas, I can't do that currently with single pass processing. Internal Context has original image dimensions, but it's not accessible. PixelSource looks like destination rather than source (it reports requested width, not original). I'm stuck.

Request: make PixelSource reflect original image properties. Add PixelDestination with resulting image size and other properties.

Thanks,
MK

**Comment by saucecontrol** [comment]
> Given an NxN box it needs to resize image to fit (preserving aspect ratio), but keep images smaller than NxN pixels intact (pass-thru).

[`CropScaleMode.Max`](https://docs.photosauce.net/api/PhotoSauce.MagicScaler.CropScaleMode.html) does this automatically now. (This was a change in v0.10 -- previously `Max` allowed upscale)

> Request: make PixelSource reflect original image properties

`PixelSource` doesn't represent the pixels in the source image.  It is intended to be used as a *source of pixels*, to allow you retrieve pixels from the pipeline post-processing, in the event you don't want to send them directly to the encoder.

You can retrieve the original image dimensions by using [`ImageFileInfo.Load`](https://docs.photosauce.net/api/PhotoSauce.MagicScaler.ImageFileInfo.html#PhotoSauce_MagicScaler_ImageFileInfo_Load_System_IO_Stream_) if you really need them.

**Comment by mikekov** [comment]
I tried box "Max" and "Contain" rescaling modes in MS 0.10.3.0 and result was the same: image gets magnified. Am I missing something obvious? I can attach code.

**Comment by saucecontrol** [comment]
Yes, please.  If `Max` isn't working as documented, that would be a bug.  I'll need repro code and image.

**Comment by mikekov** [comment]
I think I know... I need to specify *both* width and height. I was only providing "Width"...

**Comment by saucecontrol** [comment]
Ah yes, that would do it :)

**Comment by mikekov** [comment]
Cool! May I suggest changing comment for "Max":

Preserve the aspect ratio of the input image. Reduce one or both of the output
 dimensions if necessary to preserve the ratio but never enlarge **image.**
**Both dimensions must be provided**.

Thanks!

**Comment by saucecontrol** [comment]
Yeah, I'll either fix up the documentation or possibly relax that requirement.  Need to think through the scenarios around that.  Thanks for the feedback!

**Comment by mikekov** [comment]
Thank you, please feel free to close the issue.

**Comment by saucecontrol** [comment]
I went ahead and changed the settings normalization so that only `Pad` and `Stretch` modes require both width and height.  v0.11 is on NuGet now with the updated behavior.
