### ISSUE TITLE
How to resize multiple image folder?

### ISSUE THREAD

**Issue by AdwardNguyen** [saucecontrol/PhotoSauce#46]
My project has many different image directories. 
Ex: 
/assets/images/product
/assets/images/gallery
/assets/images/user

How to configure to use? Because currently you only allow one specified directory.

**Comment by saucecontrol** [comment]
I'm not sure I understand the question.  The WebRSize config allows for multiple image folders. For example:

```XML
<webrsize>
    <diskCache path="/imagecache" />
    <imageFolders>
        <add name="product" path="/assets/images/product/" />
        <add name="gallery" path="/assets/images/gallery/" />
        <add name="user"    path="/assets/images/user/" />
    </imageFolders>
</webrsize>
```
