### ISSUE TITLE
"PhotoSauce.MagicScaler.Interop.Wic" type initial value setting item throws an exception.

### ISSUE THREAD

**Issue by 0x07f** [saucecontrol/PhotoSauce#48]
PhotoSauce.MagicScaler.WicImageDecoder.<>c.<Load>b__2_0(String fn)
   PhotoSauce.MagicScaler.WicImageDecoder.createDecoder[T](Func`2 factory, T arg)
   PhotoSauce.MagicScaler.WicImageDecoder.Load(String fileName, PipelineContext ctx)
   PhotoSauce.MagicScaler.MagicImageProcessor.ProcessImage(String imgPath, Stream outStream, ProcessImageSettings settings)

```
int dHeight = 1920;
int dWidth = 1374;
int quality = 70; 
var settings = new ProcessImageSettings()
            {
                Width = dWidth,
                Height = dHeight,
                JpegQuality = quality
            };

            using (var output = new FileStream(dFile, FileMode.Create))
            {
                MagicImageProcessor.ProcessImage(sFile, output, settings);
            }
```

Work on win7 32-bit system
I can't understand the problem with this error

**Comment by saucecontrol** [comment]
You haven't given much to go on, but I would guess it's one of two things:

1) You may have an assembly version conflict between one of the MagicScaler NuGet dependencies and some other package (probably System.Memory or System.Buffers).  See: https://github.com/saucecontrol/PhotoSauce/issues/36 for some troubleshooting tips and a possible fix with binding redirects (your versions may be different).

2) You may be missing the required WIC version. On Windows 7, you must have the Windows Platform Update installed: https://www.microsoft.com/en-us/download/details.aspx?id=36805

If neither of those ideas gets you unstuck, I'll need more information to help.  You should include the minimum information necessary for me to reproduce the problem.  For example:  What version of the MagicScaler NuGet package are you using?  What target framework (.NET Framework or .NET Core version) are you building for?  What image are you trying to open?

**Comment by 0x07f** [comment]
> You haven't given much to go on, but I would guess it's one of two things:
> 
> 1. You may have an assembly version conflict between one of the MagicScaler NuGet dependencies and some other package (probably System.Memory or System.Buffers).  See: #36 for some troubleshooting tips and a possible fix with binding redirects (your versions may be different).
> 2. You may be missing the required WIC version. On Windows 7, you must have the Windows Platform Update installed: https://www.microsoft.com/en-us/download/details.aspx?id=36805
> 
> If neither of those ideas gets you unstuck, I'll need more information to help. You should include the minimum information necessary for me to reproduce the problem. For example: What version of the MagicScaler NuGet package are you using? What target framework (.NET Framework or .NET Core version) are you building for? What image are you trying to open?

Thank you, I solved my problem with the first suggestion, I cleaned up the useless references, and there will be no errors after running.
