### ISSUE TITLE
Calling MagicImageProcessor.ProcessImage() a second time results in a COM error

### ISSUE THREAD

**Issue by Metritutus** [saucecontrol/PhotoSauce#49]
The byte arrays are for the separate images and are not related (in case that's relevant).

The first run through the code seems to work perfectly.  The second run through throws an `InvalidComObjectException`.

The error: `System.Runtime.InteropServices.InvalidComObjectException: 'COM object that has been separated from its underlying RCW cannot be used.'`

The stack trace from the call to `MagicImageProcessor.ProcessImage()`:
``` 
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at PhotoSauce.Interop.Wic.IWICImagingFactory.CreateDecoderFromStream(IStream pIStream, Guid[] pguidVendor, WICDecodeOptions metadataOptions)
   at PhotoSauce.MagicScaler.WicImageDecoder.<>c.<Load>b__3_0(IStream stm)
   at PhotoSauce.MagicScaler.WicImageDecoder.createDecoder[T](Func`2 factory, T arg)
   at PhotoSauce.MagicScaler.WicImageDecoder.Load(Stream inStream, PipelineContext ctx)
   at PhotoSauce.MagicScaler.MagicImageProcessor.ProcessImage(Stream imgStream, Stream outStream, ProcessImageSettings settings)
```

The code used:
```c#
public (byte[] bytes, int width, int height) CompressBitmapImage(byte[] uncompressedBitmapBytes)
{
  byte[] compressedBytes = new byte[] { };

  using(var inputStream = new MemoryStream(uncompressedBitmapBytes))
  using(var outputStream = new MemoryStream())
  {
      var result = MagicImageProcessor.ProcessImage(inputStream, outputStream, new ProcessImageSettings() { SaveFormat=FileFormat.Jpeg, JpegQuality = 80 });
      outputStream.Position = 0;

      using (BinaryReader binaryReader = new BinaryReader(outputStream))
      {
          compressedBytes = binaryReader.ReadBytes((int)outputStream.Length);
      }

      return (compressedBytes, result.Settings.Width, result.Settings.Height);
  }
}
```

The intention of the code is to compress an image.  What am I doing wrong?

This is running in a .NET Core 3.1 project under Windows 10.

**Comment by saucecontrol** [comment]
I don't see anything that would cause that error.  I put together a quick sample with a cleaned up version of your method, and it runs fine locally.

```C#
using System;
using System.IO;
using System.Net.Http;

using PhotoSauce.MagicScaler;

class Program
{
  static void Main()
  {
    DownloadAndCompress();
  }

  public static async void DownloadAndCompress()
  {
    var client = new HttpClient();
    var img1 = await client.GetByteArrayAsync("https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Evolution_of_a_Tornado.jpg/1024px-Evolution_of_a_Tornado.jpg");
    var img2 = await client.GetByteArrayAsync("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Mountain_child.jpg/1024px-Mountain_child.jpg");

    var compressed1 = CompressBitmapImage(img1);
    var compressed2 = CompressBitmapImage(img2);
  }

  public static (byte[] bytes, int width, int height) CompressBitmapImage(byte[] uncompressedBitmapBytes)
  {
    using(var inputStream = new MemoryStream(uncompressedBitmapBytes))
    using(var outputStream = new MemoryStream())
    {
      var result = MagicImageProcessor.ProcessImage(inputStream, outputStream, new ProcessImageSettings() { SaveFormat=FileFormat.Jpeg, JpegQuality = 80 });

      return (outputStream.ToArray(), result.Settings.Width, result.Settings.Height);
    }
  }
}
```

Do you have a full sample that reproduces the error I can run?

**Comment by Metritutus** [comment]
Sorry for the late reply.  I cannot easily create a full sample, unfortunately.  The image data is being supplied using NTwain, which is interfacing with a scanner to scan an image, and I cannot supply the scanning code..

What I can say though is that the image data is received in the `Ntwain.ITwainSession.DataTransferred` event, using `NTwain.DatatransferredEventArgs.GetNativeImageStream()`.  The stream data is inserted into a byte[] array as follows:

```c#
byte[] imageBytes = new byte[] { };

using (var binaryReader = new BinaryReader(stream))
{
    imageBytes = binaryReader.ReadBytes((Int32)stream.Length);
}
```

This `imageBytes` array is then passed into the method supplied in the first post of this issue.  Unfortunately, I have been unable to replicate this outside of the main project and the scanning functionality it contains, however the issue was always replicable in said project as originally described. 

Also, in case it helps, the code supplied was the only use of `MagicImageProcessor`. in the project.

We have since switched to using SkiaSharp to compress the images (for now at least), and it all appears to function without error, however I have a separate branch with the MagicScaler code so that, should you wish me to test any other situations here to try and track down this issue, I can attempt to do so when I have the time.

**Comment by saucecontrol** [comment]
Thanks for the followup and additional details.  The error you saw is definitely something that could originate in the MagicScaler pipeline, as it releases any COM references it uses on `Dispose` (which is called internally at the end of `ProcessImage`) rather than waiting for them to be released by the RCW finalizers.  That said, it's not something I've seen before, even in deployments that process hundreds of thousands of images a day.

The next diag step if you have time to look at it further would be to identify the image type and the WIC codec that handles it on that machine.  My guess would be it's not one of the built-in WIC codecs but rather one that is installed with the scanner software.  You can check the codec by saving your stream to a file and opening it in WIC Explorer (zip attached, or you can build your own copy from https://github.com/vbaderks/WICExplorer).  If you run that on the machine where MagicScaler is failing, it should give you some basic information about the codec and vendor.

![image](https://user-images.githubusercontent.com/7929102/86287992-12089280-bb9e-11ea-978e-12a859e5a563.png)
[WICExplorer.zip](https://github.com/saucecontrol/PhotoSauce/files/4860279/WICExplorer.zip)

**Comment by saucecontrol** [comment]
Closing this one as the WIC interop no longer uses runtime-created RCWs.
