### ISSUE TITLE
Can I use this library to make an on the fly image processing?

### ISSUE THREAD

**Issue by haiduong87** [saucecontrol/PhotoSauce#58]
Hi,
I want to have an online image processing service, my main purpose are: resize + watermark.

I was looking for a fast solution, and found: 
- https://github.com/imgproxy/imgproxy 
- Or https://github.com/h2non/imaginary
Both of them are great, but I don't know go.

And I found this library.
Is this library suitable for my purposes? 

Thank you.

Duong Nguyen

**Comment by saucecontrol** [comment]
This library is primarily focused on high-performance image cropping, resizing, rotation, and basic filtering.  There are a number of high-volume services using it for on-the-fly web image processing.  It currently doesn't have any built-in functionality for watermarking, but that can be built by integrating with a more graphics-focused library such as SkiaSharp.

**Comment by haiduong87** [comment]
Thank you!
I will try to integrate with SkiaSharp
