### ISSUE TITLE
ArgumentOutOfRangeException in ColorProfileReader.cs

### ISSUE THREAD

**Issue by neelabo** [saucecontrol/PhotoSauce#6]
ArgumentOutOfRangeException at

    > src/MagicScaler/Core/ColorProfileReader.cs: 49
    CreateDate = new DateTime(rdr.ReadBigEndianUInt16(), rdr.ReadBigEndianUInt16(), rdr.ReadBigEndianUInt16(), rdr.ReadBigEndianUInt16(), rdr.ReadBigEndianUInt16(), rdr.ReadBigEndianUInt16());

This is the image where the problem occurs.

![magicscalerexception](https://user-images.githubusercontent.com/16382967/28680794-608ae6b8-7332-11e7-846e-28050c0d907c.jpg)

I hope to be able to convert this image as well. Thank you.

**Comment by saucecontrol** [comment]
Thanks for reporting that.  I've put a fix in the 0.8.0-beta3 build https://www.nuget.org/packages/PhotoSauce.MagicScaler/0.8.0-beta3
