### ISSUE TITLE
[Feature Request] Managed HEIC Decoder, Keep stream open after use.

### ISSUE THREAD

**Issue by iamcarbon** [saucecontrol/PhotoSauce#83]
The HEIC decoder auto-disposes the stream after use. Existing decoders keep the stream open after use.

We should consider leaving the stream open for consistency or add an overload to allow the stream to be left open and reused for additional operations.

Here's the use case:

```
 var info = ImageFileInfo.Load(heicStream);
 
 stream.Position = 0; // Object Disposed Exception. Unable to reuse stream

```

**Comment by saucecontrol** [comment]
Oof, that should definitely not be assuming ownership of the stream.  I'll go ahead and push a new package for that.

**Comment by saucecontrol** [comment]
New package is up.  Thanks for the quick feedback on that!
