### ISSUE TITLE
Image format not supported exception with test heic file

### ISSUE THREAD

**Issue by cvdsoftware** [saucecontrol/PhotoSauce#89]
I'm trying to convert sample1.heic from https://filesamples.com/formats/heic ([image1.zip](https://github.com/saucecontrol/PhotoSauce/files/9071663/image1.zip)) using the latest version from nuget (PhotoSauce.MagicScaler 0.13.0 and PhotoSauce.NativeCodecs.Libheif 1.12.0-Preview2) on .NET 6.0:

```csharp
CodecManager.Configure(codecs => {
    var wicheif = codecs.OfType<IImageDecoderInfo>().FirstOrDefault(c => c.MimeTypes.Any(m => m == ImageMimeTypes.Heic));
    if (wicheif != null)
        codecs.Remove(wicheif);

    codecs.UseLibheif();
});

MagicImageProcessor.ProcessImage(@"c:\temp\heic\image1.heic", @"c:\temp\heic\image1.jpg", new ProcessImageSettings { Width = 240, Height = 240, ResizeMode = CropScaleMode.Max, EncoderOptions = new JpegEncoderOptions() { Quality = 80 } });
```

But I receive a exception: System.IO.InvalidDataException: 'Image format not supported.  Please ensure the input file is an image and that a codec capable of reading the image is registered.' Other test heic files works fine with the test code.

If I disable the Libheif native codec it works on Windows 10 (but Windows Server doesn't have the codec), also the Windows Photo app can show the file:
![image](https://user-images.githubusercontent.com/2852422/177984422-16a0bd9a-6ef4-4a97-b8ed-13369781c783.png)

I don't now if this is just a coincidence or a bug in the native codec.

Btw, thanks for your great lib!

**Comment by cvdsoftware** [comment]
Sorry for my late response, was on vacation.

Your fix works perfectly, thanks for the quick response!

**Comment by saucecontrol** [comment]
Thanks for confirming.  I've published a new package with the additional signature (and which no longer requires manually removing the Windows HEIF codec before registering the plugin) https://www.nuget.org/packages/PhotoSauce.NativeCodecs.Libheif
