### ISSUE TITLE
CMYK images fail conversion when missing color profile with non-WIC codecs

### ISSUE THREAD

**Issue by iamcarbon** [saucecontrol/PhotoSauce#98]
We've recently seen an increased number of photos exported from Photoshop using 32bpp CMYK. 

Unsure how common this pixel format is... but throwing on the radar. 

I'll report back on some more statistics soon.

**Comment by saucecontrol** [comment]
Per offline convo, the issue looks to be specific to CMYK images missing their color profile when decoding with the plugin codecs.  Will add a default profile to use in these cases.

**Comment by saucecontrol** [comment]
https://github.com/saucecontrol/PhotoSauce/commit/154e4249895196348f93973fb3892eab3006d59a should take care of it

**Comment by iamcarbon** [comment]
Fix confirmed.
